import type { NextPage } from "next";
import Head from "next/head";
import ProductCard from "../components/productCard";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const products = trpc.product.allProducts.useQuery();

  return (
    <>
      <Head>
        <link rel="shortcut icon" href="/favicon.ico" />
        <title>AAAA</title>
        <meta name="description" content="Generated by create-t3-app" />
      </Head>
      <main>
        <div className="m-3 grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 xl:grid-cols-7 2xl:grid-cols-10">
          {products.data?.map((value, key) => (
            <div key={key}>
              <ProductCard
                name={value.name}
                image={value.image}
                price={value.price}
              />
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
